language: python

os:
  - linux
  # disabled since travis CI doesn't support python build on OSX and Window
  # (https://docs.travis-ci.com/user/languages/python/)
  # - osx

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - valgrind

# before_install:
#   - [ "$TRAVIS_OS_NAME" = "osx" ] && brew update
#   - [ "$TRAVIS_OS_NAME" = "osx" ] && brew install valgrind

install:
  - pip install -e .
  - pip install -r requirements.txt
  - git clone --recurse-submodule https://github.com/ouaisbrefbams/minishell /tmp/minishell
  - sed -i 's/-Werror//' /tmp/minishell/Makefile /tmp/minishell/libft/Makefile

script:
  - python -m flake8 minishell_test
  - python -m mypy minishell_test
  - python -m minishell_test -p /tmp/minishell
  - python -m minishell_test -p /tmp/minishell -k pwd
