#!/usr/bin/env python3

import os
import sys
import subprocess

from src.config import MINISHELL_DIR, MINISHELL_EXEC, EXECUTABLES_PATH


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage {} command".format(sys.argv[0]))
        sys.exit(1)
    print("=================== RUNNING " + sys.argv[1])
    process = subprocess.Popen(
        [os.path.join(MINISHELL_DIR, MINISHELL_EXEC), "-c", sys.argv[1]],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        env={"PATH": EXECUTABLES_PATH, "TERM": "xterm-256color"}
    )
    out, _ = process.communicate()
    print(out.decode())
